mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),
    path('', include("questions.urls")),
]

mysite/questions/urls.py
from django.urls import path

from .views import (
    AskedQuestionListView,
    LikedQuestionListView,
    QuestionCreateView,
    QuestionListByAnswerCount,
    QuestionListByLikesCount,
    QuestionListView,
    QuestionUpdateView,
    UnansweredQuestionListView,
    question_detail,
    question_like,
    question_report,
    recent_user_answers,
    recent_user_questions,
    specific_user_detail,
)

urlpatterns = [
    path('', QuestionListView.as_view(), name="index"),
    path('q/create/', QuestionCreateView.as_view(), name="question_create"),
    path('q/<int:pk>/', question_detail, name="question_detail"),
    path('q/<int:pk>/edit', QuestionUpdateView.as_view(),
         name="question_edit"),
    path('q/<int:pk>/like', question_like,
         name="question_like"),
    path('q/<int:pk>/report', question_report,
         name="question_report"),




    path('user/<str:user_name>/questions', recent_user_questions,
         name="user_questions_list"),
    path('user/<str:user_name>/answers', recent_user_answers,
         name="user_answers_list"),
    path('user/<str:user_name>/', specific_user_detail,
         name="user_detail"),



    path('view/mostanswered', QuestionListByAnswerCount.as_view(),
         name="sort_by_ans_count"),
    path('view/mostliked', QuestionListByLikesCount.as_view(),
         name="sort_by_likes_count"),
    path('view/asked', AskedQuestionListView.as_view(),
         name="asked_by_user"),
    path('view/liked', LikedQuestionListView.as_view(),
         name="liked_questions_list"),
    path('view/unanswered', UnansweredQuestionListView.as_view(),
         name="unanswered_questions_list"),
]

mysite/questions/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.shortcuts import reverse

User = get_user_model()


class QuestionLikes(models.Model):
    time = models.DateTimeField(auto_now_add=True)
    question = models.ForeignKey("Question", on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class QuestionReport(models.Model):
    time = models.DateTimeField(auto_now_add=True)
    question = models.ForeignKey("Question", on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    report_description = models.TextField(
        "Report if you think this question is abusing our service.",
        max_length=256,
        help_text="Required. 256 characters or fewer."
    )

    def __str__(self):
        return f"{self.user}  Reported {self.question}"


class Question(models.Model):
    question_text = models.CharField(
        max_length=128,
        help_text="This is your question. Required. 128 characters or fewer."
    )
    question_description = models.TextField(
        blank=True,
        null=True,
        max_length=256,
        help_text="""
            Describe your question and provide extra details if necessary.
            Optional.
            256 characters or fewer.
        """
    )
    asked_by = models.ForeignKey(User, on_delete=models.CASCADE)
    asked_datetime = models.DateTimeField(auto_now=False, auto_now_add=True)
    edited_datetime = models.DateTimeField(auto_now=True, auto_now_add=False)
    likes = models.ManyToManyField(
        User, through=QuestionLikes, related_name="likes"
    )

    def __str__(self):
        return self.question_text

    def get_absolute_url(self):
        return reverse("question_detail", kwargs={"pk": self.pk})

    class Meta:
        ordering = ['-asked_datetime']


class Answer(models.Model):
    answer_text = models.TextField(
        help_text="Required. 256 characters or fewer.",
        max_length=256
    )
    answer_for = models.ForeignKey(Question, on_delete=models.CASCADE)
    answered_by = models.ForeignKey(User, on_delete=models.CASCADE)
    answered_datetime = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return self.answer_text

    class Meta:
        ordering = ['-answered_datetime']

mysite/questions/forms.py
from django import forms
from django.contrib.auth import get_user_model

from .models import Answer, Question, QuestionReport

User = get_user_model()


class QuestionCreateForm(forms.ModelForm):

    class Meta:
        model = Question
        fields = ("question_text", "question_description")


class AnswerCreateForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ("answer_text",)


class UserEditForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email", ]


class QuestionReportForm(forms.ModelForm):
    class Meta:
        model = QuestionReport
        fields = ["report_description"]

mysite/questions/views.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Count
from django.http import HttpResponseForbidden, JsonResponse
from django.shortcuts import Http404, get_object_or_404, redirect, render
from django.views.generic import CreateView, ListView, UpdateView

from .forms import AnswerCreateForm, QuestionCreateForm, QuestionReportForm
from .models import Answer, Question

User = get_user_model()


class QuestionListView(ListView):
    template_name = "questions/index.html"
    model = Question
    paginate_by = settings.PAGINATE_BY


class QuestionListByAnswerCount(ListView):
    template_name = "questions/index.html"
    queryset = Question.objects.annotate(
        ans_count=Count('answer')
    ).order_by("-ans_count")

    paginate_by = settings.PAGINATE_BY


class QuestionListByLikesCount(ListView):
    template_name = "questions/index.html"
    queryset = Question.objects.annotate(
        like_count=Count('likes')
    ).order_by("-like_count")

    paginate_by = settings.PAGINATE_BY


class AskedQuestionListView(LoginRequiredMixin, ListView):
    template_name = "questions/index.html"
    paginate_by = settings.PAGINATE_BY

    def get_queryset(self):
        return Question.objects.filter(asked_by=self.request.user)


class LikedQuestionListView(LoginRequiredMixin, ListView):
    template_name = "questions/index.html"
    paginate_by = settings.PAGINATE_BY

    def get_queryset(self):
        return Question.objects.filter(likes=self.request.user)


class UnansweredQuestionListView(LoginRequiredMixin, ListView):
    template_name = "questions/index.html"
    paginate_by = settings.PAGINATE_BY

    def get_queryset(self):
        return Question.objects.filter(answer=None)


class QuestionCreateView(LoginRequiredMixin, CreateView):
    form_class = QuestionCreateForm
    template_name = 'questions/create.html'

    def form_valid(self, form):
        form.instance.asked_by = User.objects.get(username=self.request.user)
        return super().form_valid(form)


class QuestionUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Question
    template_name = "questions/update.html"
    fields = ["question_text", "question_description"]

    def test_func(self):
        return self.request.user == self.get_object().asked_by

    def form_valid(self, form):
        if self.request.user == form.instance.asked_by:
            return super().form_valid(form)
        else:
            return HttpResponseForbidden("Not allowed")


def question_detail(request, pk):
    template_name = "questions/detail.html"
    question = get_object_or_404(Question, pk=pk)
    answers = Answer.objects.filter(answer_for=question)
    form = AnswerCreateForm(request.POST or None)
    if form.is_valid() and request.user.is_authenticated:
        form.instance.answer_for = question
        form.instance.answered_by = request.user
        form.save()
        form = AnswerCreateForm()
    context = {
        "object": question,
        "answers": answers,
        "form": form
    }
    return render(request, template_name, context)


@login_required
def recent_user_questions(request, user_name):
    template_name = "user/questions.html"
    try:
        user = User.objects.get(username=user_name)
    except User.DoesNotExist:
        raise Http404
    queryset = Question.objects.filter(asked_by=user)[:5]
    context = {
        "object_list": queryset,
        "user": user
    }
    return render(request, template_name, context)


@login_required
def recent_user_answers(request, user_name):
    template_name = "user/answers.html"
    try:
        user = User.objects.get(username=user_name)
    except User.DoesNotExist:
        raise Http404
    queryset = Answer.objects.filter(answered_by=user)[:5]
    context = {
        "object_list": queryset,
        "user": user
    }
    return render(request, template_name, context)


@login_required
def specific_user_detail(request, user_name):
    template_name = "user/detail.html"
    try:
        user = User.objects.get(username=user_name)

    except User.DoesNotExist:
        raise Http404

    context = {

        "user": user
    }
    return render(request, template_name, context)


@login_required
def question_like(request, pk):
    if request.method == 'POST':

        user = request.user
        r = {"pk": pk, "Action": None}
        try:
            question = Question.objects.get(pk=pk)
        except Question.DoesNotExist:
            r["Action"] = "404"
            return JsonResponse(r, status=404)

        if (question.likes.filter(username=user)):
            question.likes.remove(user)
            r["Action"] = "Like"
            return JsonResponse(r)
        else:
            question.likes.add(user)
            r["Action"] = "Unlike"
            return JsonResponse(r)
    else:
        return HttpResponseForbidden("Not allowed")


@login_required
def question_report(request, pk):
    template_name = "questions/report.html"
    user = request.user
    question = get_object_or_404(Question, pk=pk)
    form = QuestionReportForm(request.POST or None)
    if form.is_valid():
        form.instance.question = question
        form.instance.user = user
        form.save()
        return redirect(question_detail, pk=pk)
    context = {
        "form": form
    }
    return render(request, template_name, context)

mysite/templates/user/answers.html
{% extends "base.html" %} {% block content %}

<div class="container">
    <br />
    <h1 class="text-center">Recent Answers by {{ user.username }}</h1>
    {% for answer in object_list %}
    <div class="shadow card border-primary mt-4 col-12 col-md-10 col-lg-8 mx-auto">
        <div class="card-body">
            <a href="{% url 'question_detail' answer.answer_for.pk %}">go to question</a>
            <p>{{answer.answer_text|linebreaks}}</p>
            <p class="text-muted text-right mb-0">
                answered by
                <a href="{% url 'user_detail' answer.answered_by %}">
                    {{answer.answered_by}}
                </a>
                <br />
                {{answer.answered_datetime|timesince}} ago
            </p>
        </div>
    </div>
    {% empty %}
    <p>Nothing Here</p>
    {% endfor %}
</div>

{% endblock %}

mysite/templates/user/detail.html
{% extends "base.html" %} {% block content %}

<div class="container ">
    <br />



    <div class="shadow card border-primary  mt-4 col-12 col-md-10 col-lg-8  mx-auto">
        <div class="card-body">
            <h1 class=> {{ user.username }}</h1>
            <br />
            <h4 class="text-muted">{{ user.get_full_name }}</h4>
            <br />
            <h4 class="text-muted"> {{ user.question_set.count}} Questions asked</h4>
            <br />
            <h4 class="text-muted"> {{ user.answer_set.count}} Answers given</h4>
            <br />
            <h4 class="text-muted">Member since : <br /> {{ user.date_joined |date:"M d, Y"}}</h4>
            <br />


            <a class="btn btn-outline-primary btn-block" href="{% url 'user_questions_list' user.username  %}">
                Recent Questions by user
            </a>
            <a class="btn btn-outline-primary btn-block" href="{% url 'user_answers_list' user.username  %}">
                Recent Answers by user
            </a>
            <br />
            {% ifequal user.username request.user.username %}
            <a class="btn btn-secondary btn-block" href="{% url 'user_profile_update' %}">
                Edit Profile
            </a>
            <a class="btn btn-secondary btn-block" href="{% url 'user_email_update' %}">
                Change Email
            </a>
            <a class="btn btn-secondary btn-block" href="{% url 'password_change' %}">
                Change Password
            </a>
            <a class="btn btn-danger btn-block" href="{% url  'logout' %}">
                Logout
            </a>

            {% endifequal %}
            <br />
        </div>
    </div>

</div>


{% endblock %}

mysite/templates/user/questions.html
{% extends "base.html" %} {% block content %}

<div class="container">
    <br />
    <h1 class="text-center">Recent Questions by {{ user.username }}</h1>
    {% for question in object_list %}
    <div class="shadow card border-primary mt-4 col-12 col-md-10 col-lg-8 mx-auto">
        <div class="card-body">
            <h4>
                <a href="{% url 'question_detail' question.pk %}">{{question.question_text}}</a>
            </h4>
            <p>{{question.question_description|linebreaks|truncatewords_html:5}}</p>
            <p class="text-muted text-right mb-0">
                asked by
                <a href="{% url 'user_detail' question.asked_by %}">{{question.asked_by}}</a>
                <br />
                {{question.asked_datetime|timesince}} ago
            </p>
        </div>
    </div>
    {% empty %}
    <p>Nothing Here</p>
    {% endfor %}
</div>

{% endblock %}